from setuptools import setup

setup(
    name='ITR',
    version='',
    packages=['venv.lib.python2.7.distutils', 'venv.lib.python2.7.encodings', 'venv.lib.python2.7.site-packages.py',
              'venv.lib.python2.7.site-packages.py._io', 'venv.lib.python2.7.site-packages.py._log',
              'venv.lib.python2.7.site-packages.py._code', 'venv.lib.python2.7.site-packages.py._path',
              'venv.lib.python2.7.site-packages.py._process', 'venv.lib.python2.7.site-packages.py._vendored_packages',
              'venv.lib.python2.7.site-packages.cv2', 'venv.lib.python2.7.site-packages.cv2.data',
              'venv.lib.python2.7.site-packages.PIL', 'venv.lib.python2.7.site-packages.pip',
              'venv.lib.python2.7.site-packages.pip._vendor', 'venv.lib.python2.7.site-packages.pip._vendor.idna',
              'venv.lib.python2.7.site-packages.pip._vendor.pep517',
              'venv.lib.python2.7.site-packages.pip._vendor.pytoml',
              'venv.lib.python2.7.site-packages.pip._vendor.certifi',
              'venv.lib.python2.7.site-packages.pip._vendor.chardet',
              'venv.lib.python2.7.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python2.7.site-packages.pip._vendor.distlib',
              'venv.lib.python2.7.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python2.7.site-packages.pip._vendor.msgpack',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.packages.rfc3986',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python2.7.site-packages.pip._vendor.colorama',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python2.7.site-packages.pip._vendor.lockfile',
              'venv.lib.python2.7.site-packages.pip._vendor.progress',
              'venv.lib.python2.7.site-packages.pip._vendor.requests',
              'venv.lib.python2.7.site-packages.pip._vendor.packaging',
              'venv.lib.python2.7.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python2.7.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python2.7.site-packages.pip._vendor.webencodings',
              'venv.lib.python2.7.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python2.7.site-packages.pip._internal', 'venv.lib.python2.7.site-packages.pip._internal.cli',
              'venv.lib.python2.7.site-packages.pip._internal.req',
              'venv.lib.python2.7.site-packages.pip._internal.vcs',
              'venv.lib.python2.7.site-packages.pip._internal.utils',
              'venv.lib.python2.7.site-packages.pip._internal.models',
              'venv.lib.python2.7.site-packages.pip._internal.commands',
              'venv.lib.python2.7.site-packages.pip._internal.operations',
              'venv.lib.python2.7.site-packages.pip._internal.distributions', 'venv.lib.python2.7.site-packages.tox',
              'venv.lib.python2.7.site-packages.tox.logs', 'venv.lib.python2.7.site-packages.tox.util',
              'venv.lib.python2.7.site-packages.tox.config', 'venv.lib.python2.7.site-packages.tox.helper',
              'venv.lib.python2.7.site-packages.tox.package', 'venv.lib.python2.7.site-packages.tox.package.builder',
              'venv.lib.python2.7.site-packages.tox.session', 'venv.lib.python2.7.site-packages.tox.session.commands',
              'venv.lib.python2.7.site-packages.tox.session.commands.run',
              'venv.lib.python2.7.site-packages.tox.interpreters',
              'venv.lib.python2.7.site-packages.tox.interpreters.windows', 'venv.lib.python2.7.site-packages.idna',
              'venv.lib.python2.7.site-packages.pytz', 'venv.lib.python2.7.site-packages.tika',
              'venv.lib.python2.7.site-packages.tika.tests', 'venv.lib.python2.7.site-packages.toml',
              'venv.lib.python2.7.site-packages.wand', 'venv.lib.python2.7.site-packages.wand.cdefs',
              'venv.lib.python2.7.site-packages.click', 'venv.lib.python2.7.site-packages.numpy',
              'venv.lib.python2.7.site-packages.numpy.ma', 'venv.lib.python2.7.site-packages.numpy.ma.tests',
              'venv.lib.python2.7.site-packages.numpy.doc', 'venv.lib.python2.7.site-packages.numpy.fft',
              'venv.lib.python2.7.site-packages.numpy.fft.tests', 'venv.lib.python2.7.site-packages.numpy.lib',
              'venv.lib.python2.7.site-packages.numpy.lib.tests', 'venv.lib.python2.7.site-packages.numpy.core',
              'venv.lib.python2.7.site-packages.numpy.core.tests', 'venv.lib.python2.7.site-packages.numpy.f2py',
              'venv.lib.python2.7.site-packages.numpy.f2py.tests', 'venv.lib.python2.7.site-packages.numpy.tests',
              'venv.lib.python2.7.site-packages.numpy.compat', 'venv.lib.python2.7.site-packages.numpy.compat.tests',
              'venv.lib.python2.7.site-packages.numpy.linalg', 'venv.lib.python2.7.site-packages.numpy.linalg.tests',
              'venv.lib.python2.7.site-packages.numpy.random', 'venv.lib.python2.7.site-packages.numpy.random.tests',
              'venv.lib.python2.7.site-packages.numpy.testing', 'venv.lib.python2.7.site-packages.numpy.testing.tests',
              'venv.lib.python2.7.site-packages.numpy.testing._private',
              'venv.lib.python2.7.site-packages.numpy.distutils',
              'venv.lib.python2.7.site-packages.numpy.distutils.tests',
              'venv.lib.python2.7.site-packages.numpy.distutils.command',
              'venv.lib.python2.7.site-packages.numpy.distutils.fcompiler',
              'venv.lib.python2.7.site-packages.numpy.matrixlib',
              'venv.lib.python2.7.site-packages.numpy.matrixlib.tests',
              'venv.lib.python2.7.site-packages.numpy.polynomial',
              'venv.lib.python2.7.site-packages.numpy.polynomial.tests', 'venv.lib.python2.7.site-packages.pyPdf',
              'venv.lib.python2.7.site-packages.wheel', 'venv.lib.python2.7.site-packages.wheel.cli',
              'venv.lib.python2.7.site-packages.Crypto', 'venv.lib.python2.7.site-packages.Crypto.IO',
              'venv.lib.python2.7.site-packages.Crypto.Hash', 'venv.lib.python2.7.site-packages.Crypto.Math',
              'venv.lib.python2.7.site-packages.Crypto.Util', 'venv.lib.python2.7.site-packages.Crypto.Cipher',
              'venv.lib.python2.7.site-packages.Crypto.Random', 'venv.lib.python2.7.site-packages.Crypto.Protocol',
              'venv.lib.python2.7.site-packages.Crypto.SelfTest', 'venv.lib.python2.7.site-packages.Crypto.SelfTest.IO',
              'venv.lib.python2.7.site-packages.Crypto.SelfTest.Hash',
              'venv.lib.python2.7.site-packages.Crypto.SelfTest.Math',
              'venv.lib.python2.7.site-packages.Crypto.SelfTest.Util',
              'venv.lib.python2.7.site-packages.Crypto.SelfTest.Cipher',
              'venv.lib.python2.7.site-packages.Crypto.SelfTest.Random',
              'venv.lib.python2.7.site-packages.Crypto.SelfTest.Protocol',
              'venv.lib.python2.7.site-packages.Crypto.SelfTest.PublicKey',
              'venv.lib.python2.7.site-packages.Crypto.SelfTest.Signature',
              'venv.lib.python2.7.site-packages.Crypto.PublicKey', 'venv.lib.python2.7.site-packages.Crypto.Signature',
              'venv.lib.python2.7.site-packages.pandas', 'venv.lib.python2.7.site-packages.pandas.io',
              'venv.lib.python2.7.site-packages.pandas.io.sas', 'venv.lib.python2.7.site-packages.pandas.io.json',
              'venv.lib.python2.7.site-packages.pandas.io.formats',
              'venv.lib.python2.7.site-packages.pandas.io.msgpack',
              'venv.lib.python2.7.site-packages.pandas.io.clipboard', 'venv.lib.python2.7.site-packages.pandas.api',
              'venv.lib.python2.7.site-packages.pandas.api.types',
              'venv.lib.python2.7.site-packages.pandas.api.extensions', 'venv.lib.python2.7.site-packages.pandas.core',
              'venv.lib.python2.7.site-packages.pandas.core.util', 'venv.lib.python2.7.site-packages.pandas.core.tools',
              'venv.lib.python2.7.site-packages.pandas.core.arrays',
              'venv.lib.python2.7.site-packages.pandas.core.dtypes',
              'venv.lib.python2.7.site-packages.pandas.core.sparse',
              'venv.lib.python2.7.site-packages.pandas.core.groupby',
              'venv.lib.python2.7.site-packages.pandas.core.indexes',
              'venv.lib.python2.7.site-packages.pandas.core.reshape',
              'venv.lib.python2.7.site-packages.pandas.core.internals',
              'venv.lib.python2.7.site-packages.pandas.core.computation',
              'venv.lib.python2.7.site-packages.pandas.util', 'venv.lib.python2.7.site-packages.pandas._libs',
              'venv.lib.python2.7.site-packages.pandas._libs.tslibs', 'venv.lib.python2.7.site-packages.pandas.tests',
              'venv.lib.python2.7.site-packages.pandas.tests.io',
              'venv.lib.python2.7.site-packages.pandas.tests.io.sas',
              'venv.lib.python2.7.site-packages.pandas.tests.io.json',
              'venv.lib.python2.7.site-packages.pandas.tests.io.parser',
              'venv.lib.python2.7.site-packages.pandas.tests.io.formats',
              'venv.lib.python2.7.site-packages.pandas.tests.io.msgpack',
              'venv.lib.python2.7.site-packages.pandas.tests.api', 'venv.lib.python2.7.site-packages.pandas.tests.util',
              'venv.lib.python2.7.site-packages.pandas.tests.frame',
              'venv.lib.python2.7.site-packages.pandas.tests.tools',
              'venv.lib.python2.7.site-packages.pandas.tests.arrays',
              'venv.lib.python2.7.site-packages.pandas.tests.arrays.sparse',
              'venv.lib.python2.7.site-packages.pandas.tests.arrays.interval',
              'venv.lib.python2.7.site-packages.pandas.tests.arrays.categorical',
              'venv.lib.python2.7.site-packages.pandas.tests.dtypes',
              'venv.lib.python2.7.site-packages.pandas.tests.dtypes.cast',
              'venv.lib.python2.7.site-packages.pandas.tests.scalar',
              'venv.lib.python2.7.site-packages.pandas.tests.scalar.period',
              'venv.lib.python2.7.site-packages.pandas.tests.scalar.interval',
              'venv.lib.python2.7.site-packages.pandas.tests.scalar.timedelta',
              'venv.lib.python2.7.site-packages.pandas.tests.scalar.timestamp',
              'venv.lib.python2.7.site-packages.pandas.tests.series',
              'venv.lib.python2.7.site-packages.pandas.tests.series.indexing',
              'venv.lib.python2.7.site-packages.pandas.tests.sparse',
              'venv.lib.python2.7.site-packages.pandas.tests.sparse.frame',
              'venv.lib.python2.7.site-packages.pandas.tests.sparse.series',
              'venv.lib.python2.7.site-packages.pandas.tests.tslibs',
              'venv.lib.python2.7.site-packages.pandas.tests.generic',
              'venv.lib.python2.7.site-packages.pandas.tests.groupby',
              'venv.lib.python2.7.site-packages.pandas.tests.groupby.aggregate',
              'venv.lib.python2.7.site-packages.pandas.tests.indexes',
              'venv.lib.python2.7.site-packages.pandas.tests.indexes.multi',
              'venv.lib.python2.7.site-packages.pandas.tests.indexes.period',
              'venv.lib.python2.7.site-packages.pandas.tests.indexes.interval',
              'venv.lib.python2.7.site-packages.pandas.tests.indexes.datetimes',
              'venv.lib.python2.7.site-packages.pandas.tests.indexes.timedeltas',
              'venv.lib.python2.7.site-packages.pandas.tests.reshape',
              'venv.lib.python2.7.site-packages.pandas.tests.reshape.merge',
              'venv.lib.python2.7.site-packages.pandas.tests.tseries',
              'venv.lib.python2.7.site-packages.pandas.tests.tseries.offsets',
              'venv.lib.python2.7.site-packages.pandas.tests.indexing',
              'venv.lib.python2.7.site-packages.pandas.tests.indexing.interval',
              'venv.lib.python2.7.site-packages.pandas.tests.indexing.multiindex',
              'venv.lib.python2.7.site-packages.pandas.tests.plotting',
              'venv.lib.python2.7.site-packages.pandas.tests.resample',
              'venv.lib.python2.7.site-packages.pandas.tests.extension',
              'venv.lib.python2.7.site-packages.pandas.tests.extension.base',
              'venv.lib.python2.7.site-packages.pandas.tests.extension.json',
              'venv.lib.python2.7.site-packages.pandas.tests.extension.arrow',
              'venv.lib.python2.7.site-packages.pandas.tests.extension.numpy_',
              'venv.lib.python2.7.site-packages.pandas.tests.extension.decimal',
              'venv.lib.python2.7.site-packages.pandas.tests.internals',
              'venv.lib.python2.7.site-packages.pandas.tests.arithmetic',
              'venv.lib.python2.7.site-packages.pandas.tests.reductions',
              'venv.lib.python2.7.site-packages.pandas.tests.computation',
              'venv.lib.python2.7.site-packages.pandas.arrays', 'venv.lib.python2.7.site-packages.pandas.compat',
              'venv.lib.python2.7.site-packages.pandas.compat.numpy', 'venv.lib.python2.7.site-packages.pandas.errors',
              'venv.lib.python2.7.site-packages.pandas.tseries', 'venv.lib.python2.7.site-packages.pandas.plotting',
              'venv.lib.python2.7.site-packages.pluggy', 'venv.lib.python2.7.site-packages.PyPDF2',
              'venv.lib.python2.7.site-packages.tabula', 'venv.lib.python2.7.site-packages.tabula.errors',
              'venv.lib.python2.7.site-packages.camelot', 'venv.lib.python2.7.site-packages.camelot.ext',
              'venv.lib.python2.7.site-packages.camelot.ext.ghostscript',
              'venv.lib.python2.7.site-packages.camelot.parsers', 'venv.lib.python2.7.site-packages.certifi',
              'venv.lib.python2.7.site-packages.chardet', 'venv.lib.python2.7.site-packages.chardet.cli',
              'venv.lib.python2.7.site-packages.urllib3', 'venv.lib.python2.7.site-packages.urllib3.util',
              'venv.lib.python2.7.site-packages.urllib3.contrib',
              'venv.lib.python2.7.site-packages.urllib3.contrib._securetransport',
              'venv.lib.python2.7.site-packages.urllib3.packages',
              'venv.lib.python2.7.site-packages.urllib3.packages.rfc3986',
              'venv.lib.python2.7.site-packages.urllib3.packages.backports',
              'venv.lib.python2.7.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python2.7.site-packages.dateutil', 'venv.lib.python2.7.site-packages.dateutil.tz',
              'venv.lib.python2.7.site-packages.dateutil.parser', 'venv.lib.python2.7.site-packages.dateutil.zoneinfo',
              'venv.lib.python2.7.site-packages.openpyxl', 'venv.lib.python2.7.site-packages.openpyxl.xml',
              'venv.lib.python2.7.site-packages.openpyxl.cell', 'venv.lib.python2.7.site-packages.openpyxl.chart',
              'venv.lib.python2.7.site-packages.openpyxl.pivot', 'venv.lib.python2.7.site-packages.openpyxl.utils',
              'venv.lib.python2.7.site-packages.openpyxl.compat', 'venv.lib.python2.7.site-packages.openpyxl.reader',
              'venv.lib.python2.7.site-packages.openpyxl.styles', 'venv.lib.python2.7.site-packages.openpyxl.writer',
              'venv.lib.python2.7.site-packages.openpyxl.drawing', 'venv.lib.python2.7.site-packages.openpyxl.formula',
              'venv.lib.python2.7.site-packages.openpyxl.comments',
              'venv.lib.python2.7.site-packages.openpyxl.workbook',
              'venv.lib.python2.7.site-packages.openpyxl.workbook.external_link',
              'venv.lib.python2.7.site-packages.openpyxl.packaging',
              'venv.lib.python2.7.site-packages.openpyxl.worksheet',
              'venv.lib.python2.7.site-packages.openpyxl.chartsheet',
              'venv.lib.python2.7.site-packages.openpyxl.formatting',
              'venv.lib.python2.7.site-packages.openpyxl.descriptors', 'venv.lib.python2.7.site-packages.pathlib2',
              'venv.lib.python2.7.site-packages.pdfminer', 'venv.lib.python2.7.site-packages.requests',
              'venv.lib.python2.7.site-packages.backports', 'venv.lib.python2.7.site-packages.backports.configparser',
              'venv.lib.python2.7.site-packages.packaging', 'venv.lib.python2.7.site-packages.pdf2image',
              'venv.lib.python2.7.site-packages.et_xmlfile', 'venv.lib.python2.7.site-packages.et_xmlfile.tests',
              'venv.lib.python2.7.site-packages.setuptools', 'venv.lib.python2.7.site-packages.setuptools.extern',
              'venv.lib.python2.7.site-packages.setuptools._vendor',
              'venv.lib.python2.7.site-packages.setuptools._vendor.packaging',
              'venv.lib.python2.7.site-packages.setuptools.command', 'venv.lib.python2.7.site-packages.pytesseract',
              'venv.lib.python2.7.site-packages.pkg_resources', 'venv.lib.python2.7.site-packages.pkg_resources.extern',
              'venv.lib.python2.7.site-packages.pkg_resources._vendor',
              'venv.lib.python2.7.site-packages.pkg_resources._vendor.packaging',
              'venv.lib.python2.7.site-packages.more_itertools',
              'venv.lib.python2.7.site-packages.more_itertools.tests',
              'venv.lib.python2.7.site-packages.sortedcontainers',
              'venv.lib.python2.7.site-packages.importlib_metadata',
              'venv.lib.python2.7.site-packages.importlib_metadata.docs',
              'venv.lib.python2.7.site-packages.importlib_metadata.tests',
              'venv.lib.python2.7.site-packages.importlib_metadata.tests.data',
              'venv.lib.python2.7.site-packages.virtualenv_support'],
    url='',
    license='',
    author='yajat',
    author_email='yajatns@gmail.com',
    description=''
)
